apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: photo-sharing
    deployment: photo-sharing-web
  name: photo-sharing-web
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: photo-sharing
      deployment: photo-sharing-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: photo-sharing
        deployment: photo-sharing-web
        role: frontend
      name: photo-sharing-web
    spec:
      containers:
        - name: photo-sharing-web
          env:
            - name: SSO_BASE_URL
              value: https://oidc.gov.bc.ca
            - name: LOG_LEVEL
              value: debug
          image: registry-web-image
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 2015
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 92Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/app-root/etc/Caddyfile
              name: config-vol
              subPath: Caddyfile
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30