apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-sharing-api
spec:
  template:
    spec:
      containers:
        - name: photo-sharing-api
          env:
            - name: MONGODB_HOST
              value: mongodb.bcb254-dev.svc