name: owasp-scanner
on:
  workflow_dispatch:
  push:
jobs:
  zap-owasp:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/owasp-scan.yaml@main
    with:
      ZAP_SCAN_TYPE: 'full' # Accepted values are base and full.
      # ZAP_TARGET_URL: https://rocketchat-bruce-59e31e-dev.apps.klab.devops.gov.bc.ca/
      # ZAP_TARGET_URL: http://scanme.nmap.org/
      ZAP_TARGET_URL: https://photo-sharing-web--bcb254-dev.apps.clab.devops.gov.bc.ca
      ZAP_DURATION: '2'
      ZAP_MAX_DURATION: '5'
      ZAP_GCP_PUBLISH: false
      # ZAP_GCP_PROJECT: owasp-scan-test  # Only required if ZAP_GCP_PUBLISH is TRUE
      # ZAP_GCP_BUCKET: 'zap-scan-results' # Only required if ZAP_GCP_PUBLISH is TRUE
   #secrets:
      #GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} # Only required if ZAP_GCP_PUBLISH is TRUE
