name: sonar-maven-scan
on:
  workflow_dispatch:
  push:
jobs:
  sonar-scan-mvn:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/sonar-scanner-mvn.yaml@main
    with:
      WORKDIR: ./tekton/demo/maven-test
### Manually Created Maven Project in Sonar Cloud ### 
      PROJECT_KEY: maven-test-bruce
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
