name: trivy-scan
on:
  workflow_dispatch:
  push:
jobs:
  trivy-scan:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/trivy-container.yaml@main
    with:
## docker image 
      IMAGE: gregnrobinson/bcgov-nginx-demo
      TAG: latest
